name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      manual_version:
        description: 'Manual version for the images (e.g., 1.0.1)'
        required: false
        default: ''

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  VERSION: ${{ github.event.inputs.manual_version || '0.1.7' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push CUDA image
      uses: docker/build-push-action@v4
      with:
        # Context should be the codebase
        context: .
        file: docker/Dockerfile.cuda-11.8
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/stretch-ai_cuda-11.8-auto:latest
          ${{ env.DOCKERHUB_USERNAME }}/stretch-ai_cuda-11.8-auto:${{ env.VERSION }}

    - name: Build and push ROS2 image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile.ros2
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/stretch-ai-ros2-bridge-auto:latest
          ${{ env.DOCKERHUB_USERNAME }}/stretch-ai-ros2-bridge-auto:${{ env.VERSION }}

